---
title: "Billboard scraper"
output: html_document
date: "2025-03-02"
---

```{r}
#install.packages("xml2")
library(xml2)
library(httr)
library(tidyverse)
```


```{r}
set_config(user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36; Diego Paroli / parolidiego@gmail.com"))
```


```{r}
link <- "https://www.billboard.com/charts/hot-100/2003-06-28/"

link_read <- read_html(link)

# Box with artist and song, but pnly first position
artistsong <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light  lrv-u-padding-l-1@mobile-max']")

song <- xml_text(xml_children(artistsong)[1])
artist <- xml_text(xml_children(artistsong)[2])


# Rest of 99 songs and artists
artistsong_99 <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']")
# ex.
song50 <- xml_text(xml_children(artistsong_99)[97])
artist50 <- xml_text(xml_children(artistsong_99)[98])
song100 <- xml_text(xml_children(artistsong_99)[197])
artist100 <- xml_text(xml_children(artistsong_99)[198])



# List of all the images data (for all the 100 songs)
image_urls <- xml_find_all(link_read, "//div[@class='lrv-a-crop-1x1 a-crop-67x100@mobile-max']/img[@class='c-lazy-image__img lrv-u-background-color-grey-lightest lrv-u-width-100p lrv-u-display-block lrv-u-height-auto']")

# Getting the image for number 1 song
image_url <- xml_attr(image_urls[[1]], "src")
# This is the default when no image is there:
# https://charts-static.billboard.com/img/1999/11/vertical-horizon-dd0-106x106.jpg 



# List of last week and number of weeks on chart (for all 100 songs) i.e. white background
weeks_info <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']/span")

# Last week - first column for the first row
last_week <- xml_text(weeks_info[[1]])

# Weeks on chart - second column for the first row
weeks_on_chart <- xml_text(weeks_info[[2]])



# List of peak positions for all 100 songs
peak_info <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']/span")
peak <- xml_text(peak_info[[1]])



# Getting the list of stats about no1 song on top of the page
no1_weeks <- xml_find_all(link_read, "//div/span[@class='c-label  a-font-primary-bold-xxl lrv-u-padding-lr-1 lrv-u-padding-t-025']")

# First on the left
last_week <- xml_text(no1_weeks[[1]])

# In the center
weeks_at_1 <- xml_text(no1_weeks[[2]])
# To fix for songs that debut directly at no.1
weeks_at_1 <- ifelse(length(no1_weeks) > 0, xml_text(no1_weeks[[2]]), NA)

# On the right
weeks_on_chart <- xml_text(no1_weeks[[3]])
```


```{r}
#Modifying artists and songs

artists <- xml_find_all(link_read, "//li/h3[@id='title-of-a-story']")
```


## Loop


 
```{r}
# Range of dates
dates <- seq(as.Date("2000-01-01"), as.Date("2024-12-31"), by="week")

# Initialize an empty list to store results
billboard_data <- list()

# Loop over dates
for (date in dates) {
  
  # System sleep
  Sys.sleep(2)
  
  # Format date for URL (YYYY-MM-DD) and paste it into the link
  date_str <- as.character(format(as.Date(date), "%Y-%m-%d"))
  link <- paste0("https://www.billboard.com/charts/hot-100/", date_str, "/")
  
  # Read html
  link_read <- read_html(link)
  
  # Artist and song
  artistsong <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light  lrv-u-padding-l-1@mobile-max']")
  
  song <- xml_text(xml_children(artistsong)[1])
  artist <- xml_text(xml_children(artistsong)[2])
  
  
  # Image
  image_urls <- xml_find_all(link_read, "//div[@class='lrv-a-crop-1x1 a-crop-67x100@mobile-max']/img[@class='c-lazy-image__img lrv-u-background-color-grey-lightest lrv-u-width-100p lrv-u-display-block lrv-u-height-auto']")
  
  image_url <- xml_attr(image_urls[[1]], "src")
  
  
  # Last weeks and weeks on the chart info
  weeks_info <- xml_find_all(link_read, "//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']/span")
  
  last_week <- xml_text(weeks_info[[1]])
  weeks_on_chart <- xml_text(weeks_info[[2]])
  
  
  # Number of weeks at no.1
  no1_weeks <- xml_find_all(link_read, "//div/span[@class='c-label  a-font-primary-bold-xxl lrv-u-padding-lr-1 lrv-u-padding-t-025']")
  weeks_at_1 <- ifelse(length(no1_weeks) > 0, xml_text(no1_weeks[[2]]), NA)

  
  # Group data in a tibble
  data <- tibble(
    date = date_str,
    song = song,
    artist = artist,
    image_url = image_url,
    last_week = last_week,
    weeks_on_chart = weeks_on_chart,
    weeks_at_1 = weeks_at_1
  )
  
  # Append to results list
  billboard_data[[date_str]] <- data
}

# Combine all results into one dataframe
billboard_data <- bind_rows(billboard_data)

# Clean columns
billboard_clean <- billboard_data  %>% 
  mutate(across(c(song, artist, last_week, weeks_on_chart, weeks_at_1),
                ~ str_squish(.x)))

write.csv(billboard_clean, "data/billboard_data.csv")
```

